<?php

function mymodule_menu() {
  $items = array();
  
  $items['mymodule-ajax/%node/%'] = array(
    'page callback' => 'mymodule_ajax_callback',
    'access arguments' => array('access content'),
    'page arguments' => array(1,2),
  );
  
  return $items;
}

function mymodule_ajax_callback($node, $js = 'nojs') {
  if ($js == 'nojs') {
    drupal_goto('node/' . $node->nid);
  }
  $build = node_view($node);
  $html = render($build);

  $commands = array();
  $commands[] = ajax_command_html('#ajax-content-wrapper', $html);
  print ajax_render($commands);
  exit;
}